# Generated by Django 2.0.4 on 2018-08-28 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.URLField()),
                ('headline', models.CharField(max_length=200)),
                ('body', models.CharField(max_length=5000)),
                ('score', models.FloatField()),
            ],
        ),
    ]
